# Generated by Django 5.2.2 on 2025-06-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='media/profiles/default.png', upload_to='media/profiles'),
        ),
    ]
